name: make

on:
  push:
    branches: [ main ]
    paths:
      - '**.c'
      - '**.h'
      - 'src/Makefile'
      - '.github/workflows/make.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.c'
      - '**.h'
      - 'src/Makefile'
      - '.github/workflows/make.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd src && make
